const textos_ES = {
    // Articulo labels and placeholders
    'label_CodigoA': 'Código',
    'CodigoA_placeholder': 'Código generado automáticamente',
    'label_AutoresA': 'Autores',
    'AutoresA_placeholder': 'Autores separados por comas',
    'label_TituloA': 'Título',
    'TituloA_placeholder': 'Título del artículo',
    'label_ISSN': 'ISSN',
    'ISSN_placeholder': 'Formato 0000-0000',
    'label_EstadoA': 'Estado',
    'EstadoA_option_borrador': 'Borrador',
    'EstadoA_option_revision': 'En revisión',
    'EstadoA_option_publicado': 'Publicado',
    'EstadoA_placeholder_search': 'Estado (opcional)',
    'label_FicheropdfA': 'Fichero PDF actual',
    'FicheropdfA_placeholder': 'Nombre del PDF',
    'label_nuevo_FicheropdfA': 'Nuevo PDF',
    'nuevo_FicheropdfA_placeholder': 'Selecciona un PDF',
    'icon_file_link': 'Abrir fichero',
    // Articulo titles
    'text_contenido_titulo_form_articulo_ADD': 'Añadir artículo',
    'text_contenido_titulo_form_articulo_EDIT': 'Editar artículo',
    'text_contenido_titulo_form_articulo_DELETE': 'Eliminar artículo',
    'text_contenido_titulo_form_articulo_SEARCH': 'Buscar artículos',
    'text_contenido_titulo_form_articulo_SHOWCURRENT': 'Detalles del artículo',
    // Articulo table headers
    'CodigoA': 'Código',
    'AutoresA': 'Autores',
    'TituloA': 'Título',
    'ISSN': 'ISSN',
    'EstadoA': 'Estado',
    'FicheropdfA': 'PDF',
    // Articulo errors
    'CodigoA_min_size_KO': 'El código debe tener al menos 3 caracteres.',
    'CodigoA_max_size_KO': 'El código no puede superar 12 caracteres.',
    'CodigoA_format_KO': 'El código solo puede contener letras mayúsculas y números.',
    'AutoresA_min_size_KO': 'Debe indicar al menos un autor.',
    'AutoresA_max_size_KO': 'Los autores no pueden superar 200 caracteres.',
    'AutoresA_format_KO': 'Los autores solo pueden contener letras, espacios, comas, puntos o guiones.',
    'TituloA_min_size_KO': 'El título debe tener al menos 5 caracteres.',
    'TituloA_max_size_KO': 'El título no puede superar 150 caracteres.',
    'TituloA_format_KO': 'El título contiene caracteres no permitidos.',
    'ISSN_format_KO': 'El ISSN debe seguir el formato 0000-0000.',
    'EstadoA_value_KO': 'Selecciona un estado válido.',
    'FicheropdfA_required_KO': 'Debes adjuntar un PDF.',
    'FicheropdfA_type_KO': 'El fichero debe ser de tipo PDF.',
    'FicheropdfA_max_size_KO': 'El PDF supera el tamaño máximo permitido.',
    'FicheropdfA_name_KO': 'El nombre del PDF solo puede contener letras, números, guiones o puntos.',

    // Ubicacion labels and placeholders
    'label_id_site': 'Identificador del sitio',
    'id_site_placeholder': 'Identificador generado automáticamente',
    'label_site_latitud': 'Latitud',
    'site_latitud_placeholder': 'Latitud (-90 a 90)',
    'label_site_longitud': 'Longitud',
    'site_longitud_placeholder': 'Longitud (-180 a 180)',
    'label_site_altitude': 'Altitud',
    'site_altitude_placeholder': 'Altitud (-500 a 9000)',
    'label_site_locality': 'Localidad',
    'site_locality_placeholder': 'Localidad del emplazamiento',
    'label_site_provider_login': 'Proveedor',
    'site_provider_login_placeholder': 'Usuario del proveedor',
    'label_site_north_photo': 'Foto orientada al norte',
    'site_north_photo_placeholder': 'Nombre de la imagen',
    'label_nuevo_site_north_photo': 'Nueva foto norte',
    'nuevo_site_north_photo_placeholder': 'Selecciona una imagen',
    'label_site_south_photo': 'Foto orientada al sur',
    'site_south_photo_placeholder': 'Nombre de la imagen',
    'label_nuevo_site_south_photo': 'Nueva foto sur',
    'nuevo_site_south_photo_placeholder': 'Selecciona una imagen',
    'label_site_east_photo': 'Foto orientada al este',
    'site_east_photo_placeholder': 'Nombre de la imagen',
    'label_nuevo_site_east_photo': 'Nueva foto este',
    'nuevo_site_east_photo_placeholder': 'Selecciona una imagen',
    'label_site_west_photo': 'Foto orientada al oeste',
    'site_west_photo_placeholder': 'Nombre de la imagen',
    'label_nuevo_site_west_photo': 'Nueva foto oeste',
    'nuevo_site_west_photo_placeholder': 'Selecciona una imagen',
    // Ubicacion titles
    'text_contenido_titulo_form_ubicacion_ADD': 'Añadir ubicación',
    'text_contenido_titulo_form_ubicacion_EDIT': 'Editar ubicación',
    'text_contenido_titulo_form_ubicacion_DELETE': 'Eliminar ubicación',
    'text_contenido_titulo_form_ubicacion_SEARCH': 'Buscar ubicaciones',
    'text_contenido_titulo_form_ubicacion_SHOWCURRENT': 'Detalles de la ubicación',
    // Ubicacion table headers
    'id_site': 'Identificador',
    'site_latitud': 'Latitud',
    'site_longitud': 'Longitud',
    'site_altitude': 'Altitud',
    'site_locality': 'Localidad',
    'site_provider_login': 'Proveedor',
    'site_north_photo': 'Foto norte',
    'site_south_photo': 'Foto sur',
    'site_east_photo': 'Foto este',
    'site_west_photo': 'Foto oeste',
    // Ubicacion errors
    'id_site_required_KO': 'El identificador debe venir informado desde el servidor.',
    'id_site_max_size_KO': 'El identificador no puede superar 20 caracteres.',
    'id_site_format_KO': 'El identificador solo puede tener mayúsculas, números y guiones bajos.',
    'site_latitud_format_KO': 'La latitud debe ser un número.',
    'site_latitud_range_KO': 'La latitud debe estar entre -90 y 90.',
    'site_longitud_format_KO': 'La longitud debe ser un número.',
    'site_longitud_range_KO': 'La longitud debe estar entre -180 y 180.',
    'site_altitude_format_KO': 'La altitud debe ser un número.',
    'site_altitude_range_KO': 'La altitud debe estar entre -500 y 9000.',
    'site_locality_min_size_KO': 'La localidad debe tener al menos 3 caracteres.',
    'site_locality_max_size_KO': 'La localidad no puede superar 120 caracteres.',
    'site_locality_format_KO': 'La localidad solo puede contener letras, números, espacios y - , . \'',
    'site_provider_login_min_size_KO': 'El usuario del proveedor debe tener al menos 3 caracteres.',
    'site_provider_login_max_size_KO': 'El usuario del proveedor no puede superar 50 caracteres.',
    'site_provider_login_format_KO': 'El usuario del proveedor solo puede contener letras, números, puntos, guiones o guiones bajos.',
    'site_north_photo_required_KO': 'Debes adjuntar una imagen.',
    'site_north_photo_type_KO': 'La imagen debe ser JPG o PNG.',
    'site_north_photo_max_size_KO': 'La imagen supera el tamaño máximo permitido.',
    'site_north_photo_name_KO': 'El nombre de la imagen contiene caracteres no permitidos.',
    'site_south_photo_required_KO': 'Debes adjuntar una imagen.',
    'site_south_photo_type_KO': 'La imagen debe ser JPG o PNG.',
    'site_south_photo_max_size_KO': 'La imagen supera el tamaño máximo permitido.',
    'site_south_photo_name_KO': 'El nombre de la imagen contiene caracteres no permitidos.',
    'site_east_photo_required_KO': 'Debes adjuntar una imagen.',
    'site_east_photo_type_KO': 'La imagen debe ser JPG o PNG.',
    'site_east_photo_max_size_KO': 'La imagen supera el tamaño máximo permitido.',
    'site_east_photo_name_KO': 'El nombre de la imagen contiene caracteres no permitidos.',
    'site_west_photo_required_KO': 'Debes adjuntar una imagen.',
    'site_west_photo_type_KO': 'La imagen debe ser JPG o PNG.',
    'site_west_photo_max_size_KO': 'La imagen supera el tamaño máximo permitido.',
    'site_west_photo_name_KO': 'El nombre de la imagen contiene caracteres no permitidos.',

    // Alumnograduacion labels and placeholders
    'label_login': 'Login',
    'login_placeholder': 'Identificador de usuario',
    'label_password': 'Contraseña',
    'password_placeholder': 'Introduce la contraseña',
    'label_nombre': 'Nombre',
    'nombre_placeholder': 'Nombre de la persona',
    'label_apellidos': 'Apellidos',
    'apellidos_placeholder': 'Apellidos completos',
    'label_titulacion': 'Titulación',
    'titulacion_option_GREI': 'GREI',
    'titulacion_option_GRIA': 'GRIA',
    'titulacion_option_MEI': 'MEI',
    'titulacion_option_MIA': 'MIA',
    'titulacion_option_PCEO': 'PCEO',
    'titulacion_placeholder_search': 'Titulación (opcional)',
    'label_dni': 'DNI/NIE',
    'dni_placeholder': 'Documento identificativo',
    'label_direccion': 'Dirección postal',
    'direccion_placeholder': 'Dirección completa',
    'label_email': 'Correo electrónico',
    'email_placeholder': 'correo@ejemplo.com',
    'label_fotoacto': 'Foto del acto',
    'fotoacto_placeholder': 'Nombre de la foto',
    'label_nuevo_fotoacto': 'Nueva foto del acto',
    'nuevo_fotoacto_placeholder': 'Selecciona una imagen JPG',
    // Alumnograduacion titles
    'text_contenido_titulo_form_alumnograduacion_ADD': 'Añadir alumno de graduación',
    'text_contenido_titulo_form_alumnograduacion_EDIT': 'Editar alumno de graduación',
    'text_contenido_titulo_form_alumnograduacion_DELETE': 'Eliminar alumno de graduación',
    'text_contenido_titulo_form_alumnograduacion_SEARCH': 'Buscar alumnado de graduación',
    'text_contenido_titulo_form_alumnograduacion_SHOWCURRENT': 'Detalles del alumno de graduación',

    'text menu_alumnograduacion' : 'gestionar alumno graduacion',

    // Alumnograduacion table headers
    'login': 'Login',
    'nombre': 'Nombre',
    'apellidos': 'Apellidos',
    'titulacion': 'Titulación',
    'dni': 'DNI/NIE',
    'direccion': 'Dirección',
    'email': 'Correo',
    'fotoacto': 'Foto acto',
    // Alumnograduacion errors
    'login_min_size_KO': 'El login debe tener al menos 4 caracteres.',
    'login_max_size_KO': 'El login no puede superar 15 caracteres.',
    'login_format_KO': 'El login solo puede contener letras y números.',
    'password_min_size_KO': 'La contraseña debe tener al menos 8 caracteres.',
    'password_max_size_KO': 'La contraseña no puede superar 64 caracteres.',
    'password_format_KO': 'La contraseña solo puede contener letras y espacios.',
    'nombre_min_size_KO': 'El nombre debe tener al menos 2 caracteres.',
    'nombre_max_size_KO': 'El nombre no puede superar 25 caracteres.',
    'nombre_format_KO': 'El nombre solo puede contener letras y espacios.',
    'apellidos_min_size_KO': 'Los apellidos deben tener al menos 2 caracteres.',
    'apellidos_max_size_KO': 'Los apellidos no pueden superar 35 caracteres.',
    'apellidos_format_KO': 'Los apellidos solo pueden contener letras y espacios.',
    'titulacion_value_KO': 'Selecciona una titulación válida.',
    'dni_length_KO': 'El DNI/NIE debe tener exactamente 9 caracteres.',
    'dni_format_KO': 'El DNI/NIE indicado no es válido.',
    'direccion_max_size_KO': 'La dirección no puede superar 100 caracteres.',
    'direccion_format_KO': 'La dirección contiene caracteres no permitidos.',
    'email_max_size_KO': 'El correo no puede superar 40 caracteres.',
    'email_format_KO': 'El formato del correo no es válido.',
    'fotoacto_required_KO': 'Debes adjuntar una imagen JPG.',
    'fotoacto_max_size_KO': 'La imagen supera el tamaño máximo permitido.',
    'fotoacto_type_KO': 'La imagen debe ser de tipo JPG.',
    'fotoacto_name_KO': 'El nombre de la imagen solo puede contener letras, números o puntos.'
};