const textos_EN = {
    // General UI labels
    'text_titulo_app': 'ET2 Management',
    'text_titulo_menu': 'Menu',
    'menu_alumnograduacion': 'Graduation students',
    'menu_articulo': 'Articles',
    'menu_ubicacion': 'Locations',
    'label_seleccioncolumnas': 'Columns to display',
    'RECORDSET_VACIO': 'No data available',
    'text_titulo_page_articulo': 'Article management',
    'text_titulo_page_ubicacion': 'Location management',
    'text_titulo_page_alumnograduacion': 'Graduation student management',

    // Articulo labels and placeholders
    'label_CodigoA': 'Code',
    'CodigoA_placeholder': 'Auto-generated code',
    'label_AutoresA': 'Authors',
    'AutoresA_placeholder': 'Authors separated by commas',
    'label_TituloA': 'Title',
    'TituloA_placeholder': 'Article title',
    'label_TituloR': 'Journal title',
    'TituloR_placeholder': 'Journal or review title',
    'label_VolumenR': 'Volume',
    'VolumenR_placeholder': 'Volume number',
    'label_PagIniA': 'Start page',
    'PagIniA_placeholder': 'First page number',
    'label_PagFinA': 'End page',
    'PagFinA_placeholder': 'Last page number',
    'label_FechaPublicacionR': 'Publication date',
    'FechaPublicacionR_placeholder': 'YYYY-MM-DD',
    'label_ISSN': 'ISSN',
    'ISSN_placeholder': 'Format 0000-0000',
    'label_EstadoA': 'Status',
    'EstadoA_option_borrador': 'Draft',
    'EstadoA_option_revision': 'Under review',
    'EstadoA_option_publicado': 'Published',
    'EstadoA_placeholder_search': 'Status (optional)',
    'label_FicheropdfA': 'Current PDF file',
    'FicheropdfA_placeholder': 'PDF name',
    'label_nuevo_FicheropdfA': 'New PDF',
    'nuevo_FicheropdfA_placeholder': 'Choose a PDF',
    'icon_file_link': 'Open file',
    // Articulo titles
    'text_contenido_titulo_form_articulo_ADD': 'Add article',
    'text_contenido_titulo_form_articulo_EDIT': 'Edit article',
    'text_contenido_titulo_form_articulo_DELETE': 'Delete article',
    'text_contenido_titulo_form_articulo_SEARCH': 'Search articles',
    'text_contenido_titulo_form_articulo_SHOWCURRENT': 'Article details',
    // Articulo table headers
    'CodigoA': 'Code',
    'AutoresA': 'Authors',
    'TituloA': 'Title',
    'TituloR': 'Journal title',
    'VolumenR': 'Volume',
    'PagIniA': 'Start page',
    'PagFinA': 'End page',
    'FechaPublicacionR': 'Publication date',
    'ISSN': 'ISSN',
    'EstadoA': 'Status',
    'FicheropdfA': 'PDF',
    // Articulo errors
    'CodigoA_min_size_KO': 'Code must be at least 3 characters long.',
    'CodigoA_max_size_KO': 'Code cannot exceed 12 characters.',
    'CodigoA_format_KO': 'Code can only contain uppercase letters and numbers.',
    'AutoresA_min_size_KO': 'Provide at least one author.',
    'AutoresA_max_size_KO': 'Authors text cannot exceed 200 characters.',
    'AutoresA_format_KO': 'Authors may only contain letters, spaces, commas, periods or hyphens.',
    'TituloA_min_size_KO': 'Title must have at least 5 characters.',
    'TituloA_max_size_KO': 'Title cannot exceed 150 characters.',
    'TituloA_format_KO': 'Title contains invalid characters.',
    'TituloR_min_size_KO': 'The journal title must have at least 5 characters.',
    'TituloR_max_size_KO': 'The journal title cannot exceed 150 characters.',
    'TituloR_format_KO': 'The journal title contains invalid characters.',
    'VolumenR_required_KO': 'The volume is required.',
    'VolumenR_format_KO': 'The volume must contain digits only.',
    'VolumenR_range_KO': 'The volume must be between 1 and 9999.',
    'PagIniA_required_KO': 'The starting page is required.',
    'PagIniA_format_KO': 'The starting page must contain digits only.',
    'PagIniA_range_KO': 'The starting page must be between 1 and 9999.',
    'PagFinA_required_KO': 'The ending page is required.',
    'PagFinA_format_KO': 'The ending page must contain digits only.',
    'PagFinA_range_KO': 'The ending page must be between 1 and 9999.',
    'PagFinA_order_KO': 'The ending page must be greater than or equal to the starting page.',
    'FechaPublicacionR_required_KO': 'The publication date is required.',
    'FechaPublicacionR_format_KO': 'The date must use the YYYY-MM-DD format.',
    'FechaPublicacionR_value_KO': 'The provided date is not valid.',
    'ISSN_format_KO': 'ISSN must follow the 0000-0000 format.',
    'EstadoA_value_KO': 'Select a valid status.',
    'FicheropdfA_required_KO': 'You must attach a PDF file.',
    'FicheropdfA_type_KO': 'The file must be a PDF.',
    'FicheropdfA_max_size_KO': 'The PDF exceeds the maximum allowed size.',
    'FicheropdfA_name_KO': 'The PDF name may only contain letters, numbers, hyphens or dots.',

    // Ubicacion labels and placeholders
    'label_id_site': 'Site identifier',
    'id_site_placeholder': 'Auto-generated identifier',
    'label_site_latitud': 'Latitude',
    'site_latitud_placeholder': 'Latitude (-90 to 90)',
    'label_site_longitud': 'Longitude',
    'site_longitud_placeholder': 'Longitude (-180 to 180)',
    'label_site_altitude': 'Altitude',
    'site_altitude_placeholder': 'Altitude (-500 to 9000)',
    'label_site_locality': 'Locality',
    'site_locality_placeholder': 'Site locality',
    'label_site_provider_login': 'Provider user',
    'site_provider_login_placeholder': 'Provider login',
    'label_site_north_photo': 'North-facing photo',
    'site_north_photo_placeholder': 'Image name',
    'label_nuevo_site_north_photo': 'New north photo',
    'nuevo_site_north_photo_placeholder': 'Choose an image',
    'label_site_south_photo': 'South-facing photo',
    'site_south_photo_placeholder': 'Image name',
    'label_nuevo_site_south_photo': 'New south photo',
    'nuevo_site_south_photo_placeholder': 'Choose an image',
    'label_site_east_photo': 'East-facing photo',
    'site_east_photo_placeholder': 'Image name',
    'label_nuevo_site_east_photo': 'New east photo',
    'nuevo_site_east_photo_placeholder': 'Choose an image',
    'label_site_west_photo': 'West-facing photo',
    'site_west_photo_placeholder': 'Image name',
    'label_nuevo_site_west_photo': 'New west photo',
    'nuevo_site_west_photo_placeholder': 'Choose an image',
    // Ubicacion titles
    'text_contenido_titulo_form_ubicacion_ADD': 'Add location',
    'text_contenido_titulo_form_ubicacion_EDIT': 'Edit location',
    'text_contenido_titulo_form_ubicacion_DELETE': 'Delete location',
    'text_contenido_titulo_form_ubicacion_SEARCH': 'Search locations',
    'text_contenido_titulo_form_ubicacion_SHOWCURRENT': 'Location details',
    // Ubicacion table headers
    'id_site': 'Identifier',
    'site_latitud': 'Latitude',
    'site_longitud': 'Longitude',
    'site_altitude': 'Altitude',
    'site_locality': 'Locality',
    'site_provider_login': 'Provider user',
    'site_north_photo': 'North photo',
    'site_south_photo': 'South photo',
    'site_east_photo': 'East photo',
    'site_west_photo': 'West photo',
    // Ubicacion errors
    'id_site_required_KO': 'Identifier must be provided by the server.',
    'id_site_max_size_KO': 'Identifier cannot exceed 20 characters.',
    'id_site_format_KO': 'Identifier may only contain uppercase letters, numbers and underscores.',
    'site_latitud_format_KO': 'Latitude must be a numeric value.',
    'site_latitud_range_KO': 'Latitude must be between -90 and 90.',
    'site_longitud_format_KO': 'Longitude must be a numeric value.',
    'site_longitud_range_KO': 'Longitude must be between -180 and 180.',
    'site_altitude_format_KO': 'Altitude must be a numeric value.',
    'site_altitude_range_KO': 'Altitude must be between -500 and 9000.',
    'site_locality_min_size_KO': 'Locality must contain at least 3 characters.',
    'site_locality_max_size_KO': 'Locality cannot exceed 120 characters.',
    'site_locality_format_KO': 'Locality may only contain letters, numbers, spaces and - , . \'.',
    'site_provider_login_min_size_KO': 'Provider user must contain at least 3 characters.',
    'site_provider_login_max_size_KO': 'Provider user cannot exceed 50 characters.',
    'site_provider_login_format_KO': 'Provider user may only contain letters, numbers, dots, hyphens or underscores.',
    'site_north_photo_required_KO': 'You must attach an image.',
    'site_north_photo_type_KO': 'Image must be JPG or PNG.',
    'site_north_photo_max_size_KO': 'Image exceeds the maximum allowed size.',
    'site_north_photo_name_KO': 'Image name contains invalid characters.',
    'site_south_photo_required_KO': 'You must attach an image.',
    'site_south_photo_type_KO': 'Image must be JPG or PNG.',
    'site_south_photo_max_size_KO': 'Image exceeds the maximum allowed size.',
    'site_south_photo_name_KO': 'Image name contains invalid characters.',
    'site_east_photo_required_KO': 'You must attach an image.',
    'site_east_photo_type_KO': 'Image must be JPG or PNG.',
    'site_east_photo_max_size_KO': 'Image exceeds the maximum allowed size.',
    'site_east_photo_name_KO': 'Image name contains invalid characters.',
    'site_west_photo_required_KO': 'You must attach an image.',
    'site_west_photo_type_KO': 'Image must be JPG or PNG.',
    'site_west_photo_max_size_KO': 'Image exceeds the maximum allowed size.',
    'site_west_photo_name_KO': 'Image name contains invalid characters.',

    // Alumnograduacion labels and placeholders
    'label_login': 'Login',
    'login_placeholder': 'User identifier',
    'label_password': 'Password',
    'password_placeholder': 'Enter the password',
    'label_nombre': 'First name',
    'nombre_placeholder': 'Person name',
    'label_apellidos': 'Surnames',
    'apellidos_placeholder': 'Full surnames',
    'label_titulacion': 'Degree',
    'titulacion_option_GREI': 'GREI',
    'titulacion_option_GRIA': 'GRIA',
    'titulacion_option_MEI': 'MEI',
    'titulacion_option_MIA': 'MIA',
    'titulacion_option_PCEO': 'PCEO',
    'titulacion_placeholder_search': 'Degree (optional)',
    'label_dni': 'ID number',
    'dni_placeholder': 'National ID or NIE',
    'label_direccion': 'Postal address',
    'direccion_placeholder': 'Full address',
    'label_email': 'Email',
    'email_placeholder': 'user@example.com',
    'label_fotoacto': 'Ceremony photo',
    'fotoacto_placeholder': 'Photo name',
    'label_nuevo_fotoacto': 'New ceremony photo',
    'nuevo_fotoacto_placeholder': 'Choose a JPG image',
    // Alumnograduacion titles
    'text_contenido_titulo_form_alumnograduacion_ADD': 'Add graduation student',
    'text_contenido_titulo_form_alumnograduacion_EDIT': 'Edit graduation student',
    'text_contenido_titulo_form_alumnograduacion_DELETE': 'Delete graduation student',
    'text_contenido_titulo_form_alumnograduacion_SEARCH': 'Search graduation students',
    'text_contenido_titulo_form_alumnograduacion_SHOWCURRENT': 'Graduation student details',
    // Alumnograduacion table headers
    'login': 'Login',
    'nombre': 'Name',
    'apellidos': 'Surnames',
    'titulacion': 'Degree',
    'dni': 'ID number',
    'direccion': 'Address',
    'email': 'Email',
    'fotoacto': 'Ceremony photo',
    // Alumnograduacion errors
    'login_min_size_KO': 'Login must have at least 4 characters.',
    'login_max_size_KO': 'Login cannot exceed 15 characters.',
    'login_format_KO': 'Login may only contain letters and numbers.',
    'password_min_size_KO': 'Password must have at least 8 characters.',
    'password_max_size_KO': 'Password cannot exceed 64 characters.',
    'password_format_KO': 'Password may only contain letters and spaces.',
    'nombre_min_size_KO': 'Name must have at least 2 characters.',
    'nombre_max_size_KO': 'Name cannot exceed 25 characters.',
    'nombre_format_KO': 'Name may only contain letters and spaces.',
    'apellidos_min_size_KO': 'Surnames must have at least 2 characters.',
    'apellidos_max_size_KO': 'Surnames cannot exceed 35 characters.',
    'apellidos_format_KO': 'Surnames may only contain letters and spaces.',
    'titulacion_value_KO': 'Select a valid degree.',
    'dni_length_KO': 'ID must contain exactly 9 characters.',
    'dni_format_KO': 'The provided ID is not valid.',
    'direccion_max_size_KO': 'Address cannot exceed 100 characters.',
    'direccion_format_KO': 'Address contains invalid characters.',
    'email_max_size_KO': 'Email cannot exceed 40 characters.',
    'email_format_KO': 'Email format is not valid.',
    'fotoacto_required_KO': 'You must attach a JPG image.',
    'fotoacto_max_size_KO': 'Image exceeds the maximum allowed size.',
    'fotoacto_type_KO': 'Image must be JPG.',
    'fotoacto_name_KO': 'Image name may only contain letters, numbers or dots.',
    //Menu texts
    'text menu_alumnograduacion' : 'Manage Alumno Graduacion',
    'text menu_articulo' : 'Manage Articles',
    'text menu_ubicacion' : 'Manage Locations'
};