var articulo_def_tests = [
  ["articulo", "CodigoA", "input", 1, "Código requerido en alta", "ADD", "CODIGOA_REQUIRED", "Código obligatorio"],
  ["articulo", "CodigoA", "input", 2, "Código válido en alta", "ADD", true, "Código correcto"],
  ["articulo", "AutoresA", "input", 3, "Autores con caracteres permitidos", "ADD", true, "Autores correctos"],
  ["articulo", "AutoresA", "input", 4, "Autores con carácter inválido", "ADD", "AUTORESA_FORMAT_KO", "Autores solo letras y puntuación"],
  ["articulo", "PagFinA", "input", 5, "Fin de página debe ser >= inicio", "ADD", "PAGFINA_RANGE_KO", "Comprobar rango de páginas"],
  ["articulo", "ISSN", "input", 6, "ISSN debe seguir patrón oficial", "ADD", "ISSN_FORMAT_KO", "Patrón ISSN inválido"],
  ["articulo", "FechaPublicacionR", "input", 7, "Fecha obligatoria", "ADD", "FECHAPUBLICACIONR_REQUIRED", "Fecha requerida"],
  ["articulo", "EstadoA", "select", 8, "Estado debe estar en enumeración", "ADD", "ESTADOA_ENUM_KO", "Valor de estado incorrecto"],
  ["articulo", "nuevo_FicheropdfA", "file", 9, "PDF requerido en alta", "ADD", "FICHEROPDFA_FILE_REQUIRED", "Debe adjuntar PDF"],
  ["articulo", "nuevo_FicheropdfA", "file", 10, "PDF válido en alta", "ADD", true, "PDF correcto"],
  ["articulo", "CodigoA", "input", 11, "Código numérico en búsqueda", "SEARCH", "CODIGOA_FORMAT_KO", "Formato en búsqueda"],
  ["articulo", "ISSN", "input", 12, "ISSN válido en alta", "ADD", true, "ISSN correcto"],
  ["articulo", "FechaPublicacionR", "input", 13, "Fecha con formato correcto", "ADD", true, "Fecha correcta"],
  ["articulo", "EstadoA", "select", 14, "Estado válido", "ADD", true, "Estado correcto"],
  ["articulo", "PagFinA", "input", 15, "Fin de página válido", "ADD", true, "Rango correcto"],
  ["articulo", "FechaPublicacionR", "input", 16, "Fecha no puede ser futura", "ADD", "FECHAPUBLICACIONR_FUTURE_KO", "Fecha futura no permitida"],
  ["articulo", "AutoresA", "input", 17, "Autores inválidos en edición", "EDIT", "AUTORESA_FORMAT_KO", "Autores solo letras y puntuación"],
  ["articulo", "AutoresA", "input", 18, "Autores válidos en edición", "EDIT", true, "Autores correctos"],
  ["articulo", "PagFinA", "input", 19, "Fin de página inválido en edición", "EDIT", "PAGFINA_RANGE_KO", "Comprobar rango de páginas"],
  ["articulo", "PagFinA", "input", 20, "Fin de página válido en edición", "EDIT", true, "Rango correcto"],
  ["articulo", "ISSN", "input", 21, "ISSN formato incorrecto en edición", "EDIT", "ISSN_FORMAT_KO", "Patrón ISSN inválido"],
  ["articulo", "ISSN", "input", 22, "ISSN válido en edición", "EDIT", true, "ISSN correcto"],
  ["articulo", "FechaPublicacionR", "input", 23, "Fecha obligatoria en edición", "EDIT", "FECHAPUBLICACIONR_REQUIRED", "Fecha requerida"],
  ["articulo", "FechaPublicacionR", "input", 24, "Fecha no futura en edición", "EDIT", "FECHAPUBLICACIONR_FUTURE_KO", "Fecha futura no permitida"],
  ["articulo", "EstadoA", "select", 25, "Estado permitido en edición", "EDIT", "ESTADOA_ENUM_KO", "Valor de estado incorrecto"],
  ["articulo", "EstadoA", "select", 26, "Estado válido en edición", "EDIT", true, "Estado correcto"],
  ["articulo", "nuevo_FicheropdfA", "file", 27, "PDF inválido en edición", "EDIT", "FICHEROPDFA_TYPE_KO", "Tipo de fichero incorrecto"],
  ["articulo", "nuevo_FicheropdfA", "file", 28, "PDF válido en edición", "EDIT", true, "PDF correcto"],
];

var articulo_tests_fields = [
  ["articulo", "CodigoA", 1, 1, "ADD", [{ CodigoA: "" }], "CODIGOA_REQUIRED"],
  ["articulo", "CodigoA", 2, 2, "ADD", [{ CodigoA: "123" }], true],
  ["articulo", "AutoresA", 4, 3, "ADD", [{ AutoresA: "Autor#1" }], "AUTORESA_FORMAT_KO"],
  ["articulo", "AutoresA", 3, 4, "ADD", [{ AutoresA: "Autor Uno" }], true],
  [
    "articulo",
    "PagFinA",
    5,
    5,
    "ADD",
    [{ PagIniA: "10" }, { PagFinA: "5" }],
    "PAGFINA_RANGE_KO",
  ],
  ["articulo", "ISSN", 6, 6, "ADD", [{ ISSN: "1234-12X" }], "ISSN_FORMAT_KO"],
  ["articulo", "ISSN", 12, 7, "ADD", [{ ISSN: "1234-567X" }], true],
  ["articulo", "FechaPublicacionR", 7, 8, "ADD", [{ FechaPublicacionR: "" }], "FECHAPUBLICACIONR_REQUIRED"],
  ["articulo", "FechaPublicacionR", 13, 9, "ADD", [{ FechaPublicacionR: "2024-05-01" }], true],
  ["articulo", "FechaPublicacionR", 16, 10, "ADD", [{ FechaPublicacionR: "2100-01-01" }], "FECHAPUBLICACIONR_FUTURE_KO"],
  ["articulo", "EstadoA", 8, 11, "ADD", [{ EstadoA: "Borrador" }], "ESTADOA_ENUM_KO"],
  ["articulo", "EstadoA", 14, 12, "ADD", [{ EstadoA: "Enviado" }], true],
  ["articulo", "PagFinA", 15, 13, "ADD", [{ PagIniA: "5" }, { PagFinA: "15" }], true],
  ["articulo", "CodigoA", 11, 14, "SEARCH", [{ CodigoA: "ABC" }], "CODIGOA_FORMAT_KO"],
  ["articulo", "AutoresA", 17, 15, "EDIT", [{ AutoresA: "Autor#1" }], "AUTORESA_FORMAT_KO"],
  ["articulo", "AutoresA", 18, 16, "EDIT", [{ AutoresA: "Autor Uno" }], true],
  ["articulo", "PagFinA", 19, 17, "EDIT", [{ PagIniA: "12" }, { PagFinA: "6" }], "PAGFINA_RANGE_KO"],
  ["articulo", "PagFinA", 20, 18, "EDIT", [{ PagIniA: "10" }, { PagFinA: "18" }], true],
  ["articulo", "ISSN", 21, 19, "EDIT", [{ ISSN: "1234-12X" }], "ISSN_FORMAT_KO"],
  ["articulo", "ISSN", 22, 20, "EDIT", [{ ISSN: "1234-567X" }], true],
  ["articulo", "FechaPublicacionR", 23, 21, "EDIT", [{ FechaPublicacionR: "" }], "FECHAPUBLICACIONR_REQUIRED"],
  ["articulo", "FechaPublicacionR", 24, 22, "EDIT", [{ FechaPublicacionR: "2100-01-01" }], "FECHAPUBLICACIONR_FUTURE_KO"],
  ["articulo", "EstadoA", 25, 23, "EDIT", [{ EstadoA: "Borrador" }], "ESTADOA_ENUM_KO"],
  ["articulo", "EstadoA", 26, 24, "EDIT", [{ EstadoA: "Publicado" }], true],
];

var articulo_tests_files = [
  ["articulo", "nuevo_FicheropdfA", 9, 1, "ADD", "", [], "FICHEROPDFA_FILE_REQUIRED"],
  [
    "articulo",
    "nuevo_FicheropdfA",
    9,
    2,
    "ADD",
    "",
    [
      { format_name_file: "paper.pdf" },
      { type_file: "image/png" },
      { max_size_file: 500000 },
    ],
    "FICHEROPDFA_TYPE_KO",
  ],
  [
    "articulo",
    "nuevo_FicheropdfA",
    10,
    3,
    "ADD",
    "",
    [
      { format_name_file: "paper.pdf" },
      { type_file: "application/pdf" },
      { max_size_file: 500000 },
    ],
    true,
  ],
  [
    "articulo",
    "nuevo_FicheropdfA",
    27,
    4,
    "EDIT",
    "",
    [
      { format_name_file: "paper.pdf" },
      { type_file: "image/png" },
      { max_size_file: 500000 },
    ],
    "FICHEROPDFA_TYPE_KO",
  ],
  [
    "articulo",
    "nuevo_FicheropdfA",
    28,
    5,
    "EDIT",
    "",
    [
      { format_name_file: "paper.pdf" },
      { type_file: "application/pdf" },
      { max_size_file: 500000 },
    ],
    true,
  ],
];

var ubicacion_def_tests = [
  ["ubicacion", "id_site", "input", 1, "Identificador obligatorio", "ADD", "IDSITE_REQUIRED", "Id requerido"],
  ["ubicacion", "id_site", "input", 2, "Identificador válido", "ADD", true, "Id correcto"],
  ["ubicacion", "site_latitud", "input", 3, "Latitud con formato decimal", "ADD", "LATITUD_FORMAT_KO", "Formato decimal"],
  ["ubicacion", "site_longitud", "input", 4, "Longitud dentro de rango", "ADD", "LONGITUD_RANGE_KO", "Rango longitud"],
  ["ubicacion", "site_provider_login", "input", 5, "Login proveedor formato", "ADD", "PROVIDER_FORMAT_KO", "Formato proveedor"],
  ["ubicacion", "site_locality", "input", 6, "Localidad válida", "ADD", true, "Localidad correcta"],
  ["ubicacion", "site_latitud", "input", 7, "Latitud búsqueda formato", "SEARCH", "LATITUD_FORMAT_KO", "Formato búsqueda"],
  ["ubicacion", "nuevo_site_north_photo", "file", 8, "Foto norte requerida", "ADD", "SITE_NORTH_PHOTO_FILE_REQUIRED", "Foto obligatoria"],
  ["ubicacion", "nuevo_site_north_photo", "file", 9, "Foto norte válida", "ADD", true, "Foto correcta"],
  ["ubicacion", "site_latitud", "input", 10, "Latitud formato en edición", "EDIT", "LATITUD_FORMAT_KO", "Formato decimal"],
  ["ubicacion", "site_longitud", "input", 11, "Longitud rango en edición", "EDIT", "LONGITUD_RANGE_KO", "Rango longitud"],
  ["ubicacion", "site_provider_login", "input", 12, "Login proveedor formato en edición", "EDIT", "PROVIDER_FORMAT_KO", "Formato proveedor"],
  ["ubicacion", "site_locality", "input", 13, "Localidad válida en edición", "EDIT", true, "Localidad correcta"],
  ["ubicacion", "nuevo_site_north_photo", "file", 14, "Foto norte tipo incorrecto en edición", "EDIT", "SITE_NORTH_PHOTO_TYPE_KO", "Tipo de archivo inválido"],
  ["ubicacion", "nuevo_site_north_photo", "file", 15, "Foto norte válida en edición", "EDIT", true, "Foto correcta"],
];

var ubicacion_tests_fields = [
  ["ubicacion", "id_site", 1, 1, "ADD", [{ id_site: "" }], "IDSITE_REQUIRED"],
  ["ubicacion", "id_site", 2, 2, "ADD", [{ id_site: "45" }], true],
  ["ubicacion", "site_latitud", 3, 3, "ADD", [{ site_latitud: "ABC" }], "LATITUD_FORMAT_KO"],
  ["ubicacion", "site_longitud", 4, 4, "ADD", [{ site_longitud: "200.000000" }], "LONGITUD_RANGE_KO"],
  ["ubicacion", "site_provider_login", 5, 5, "ADD", [{ site_provider_login: "user name" }], "PROVIDER_FORMAT_KO"],
  ["ubicacion", "site_locality", 6, 6, "ADD", [{ site_locality: "Vigo" }], true],
  ["ubicacion", "site_latitud", 7, 7, "SEARCH", [{ site_latitud: "12,34" }], "LATITUD_FORMAT_KO"],
  ["ubicacion", "site_latitud", 10, 8, "EDIT", [{ site_latitud: "ABC" }], "LATITUD_FORMAT_KO"],
  ["ubicacion", "site_longitud", 11, 9, "EDIT", [{ site_longitud: "200.000000" }], "LONGITUD_RANGE_KO"],
  ["ubicacion", "site_provider_login", 12, 10, "EDIT", [{ site_provider_login: "user name" }], "PROVIDER_FORMAT_KO"],
  ["ubicacion", "site_locality", 13, 11, "EDIT", [{ site_locality: "Vigo" }], true],
];

var ubicacion_tests_files = [
  ["ubicacion", "nuevo_site_north_photo", 8, 1, "ADD", "", [], "SITE_NORTH_PHOTO_FILE_REQUIRED"],
  [
    "ubicacion",
    "nuevo_site_north_photo",
    9,
    2,
    "ADD",
    "",
    [
      { format_name_file: "north.jpg" },
      { type_file: "image/jpeg" },
      { max_size_file: 500000 },
    ],
    true,
  ],
  [
    "ubicacion",
    "nuevo_site_north_photo",
    14,
    3,
    "EDIT",
    "",
    [
      { format_name_file: "north.jpg" },
      { type_file: "image/gif" },
      { max_size_file: 500000 },
    ],
    "SITE_NORTH_PHOTO_TYPE_KO",
  ],
  [
    "ubicacion",
    "nuevo_site_north_photo",
    15,
    4,
    "EDIT",
    "",
    [
      { format_name_file: "north.jpg" },
      { type_file: "image/jpeg" },
      { max_size_file: 500000 },
    ],
    true,
  ],
];

var alumnograduacion_def_tests = [
  ["alumnograduacion", "login", "input", 1, "Login requerido", "ADD", "LOGIN_REQUIRED", "Login obligatorio"],
  ["alumnograduacion", "login", "input", 2, "Login mínimo 4 caracteres", "ADD", "LOGIN_MIN_SIZE_KO", "Login demasiado corto"],
  ["alumnograduacion", "login", "input", 3, "Login máximo 15 caracteres", "ADD", "LOGIN_MAX_SIZE_KO", "Login demasiado largo"],
  ["alumnograduacion", "login", "input", 4, "Login solo letras", "ADD", "LOGIN_FORMAT_KO", "Solo letras sin espacios"],
  ["alumnograduacion", "login", "input", 5, "Login válido", "ADD", true, "Login correcto"],
  ["alumnograduacion", "login", "input", 6, "Búsqueda login vacía", "SEARCH", true, "Se permite búsqueda vacía"],
  ["alumnograduacion", "login", "input", 7, "Búsqueda login formato inválido", "SEARCH", "LOGIN_FORMAT_KO", "Solo letras en búsqueda"],
  ["alumnograduacion", "login", "input", 8, "Búsqueda login demasiado largo", "SEARCH", "LOGIN_MAX_SIZE_KO", "Máximo 15 caracteres en búsqueda"],
  ["alumnograduacion", "login", "input", 9, "Búsqueda login válida", "SEARCH", true, "Subcadena válida"],

  ["alumnograduacion", "password", "input", 10, "Password requerida", "ADD", "PASSWORD_REQUIRED", "Contraseña obligatoria"],
  ["alumnograduacion", "password", "input", 11, "Password mínima 8 caracteres", "ADD", "PASSWORD_MIN_SIZE_KO", "Contraseña demasiado corta"],
  ["alumnograduacion", "password", "input", 12, "Password máximo 64 caracteres", "ADD", "PASSWORD_MAX_SIZE_KO", "Contraseña demasiado larga"],
  ["alumnograduacion", "password", "input", 13, "Password solo letras y dígitos", "ADD", "PASSWORD_FORMAT_KO", "Sin símbolos"],
  ["alumnograduacion", "password", "input", 14, "Password válida", "ADD", true, "Password correcta"],
  ["alumnograduacion", "password", "input", 15, "Búsqueda password vacía", "SEARCH", true, "Filtro opcional"],
  ["alumnograduacion", "password", "input", 16, "Búsqueda password formato", "SEARCH", "PASSWORD_FORMAT_KO", "Sin símbolos en búsqueda"],
  ["alumnograduacion", "password", "input", 17, "Búsqueda password demasiado larga", "SEARCH", "PASSWORD_MAX_SIZE_KO", "Máximo 64 en búsqueda"],
  ["alumnograduacion", "password", "input", 18, "Búsqueda password válida", "SEARCH", true, "Subcadena válida"],

  ["alumnograduacion", "nombre", "input", 19, "Nombre requerido", "ADD", "NOMBRE_REQUIRED", "Nombre obligatorio"],
  ["alumnograduacion", "nombre", "input", 20, "Nombre solo letras y espacios", "ADD", "NOMBRE_FORMAT_KO", "Formato de nombre inválido"],
  ["alumnograduacion", "nombre", "input", 21, "Nombre mínimo 2 caracteres", "ADD", "NOMBRE_MIN_SIZE_KO", "Nombre demasiado corto"],
  ["alumnograduacion", "nombre", "input", 22, "Nombre máximo 25 caracteres", "ADD", "NOMBRE_MAX_SIZE_KO", "Nombre demasiado largo"],
  ["alumnograduacion", "nombre", "input", 23, "Nombre válido", "ADD", true, "Nombre correcto"],
  ["alumnograduacion", "nombre", "input", 24, "Búsqueda nombre vacía", "SEARCH", true, "Filtro opcional"],
  ["alumnograduacion", "nombre", "input", 25, "Búsqueda nombre formato", "SEARCH", "NOMBRE_FORMAT_KO", "Solo letras en búsqueda"],
  ["alumnograduacion", "nombre", "input", 26, "Búsqueda nombre máximo", "SEARCH", "NOMBRE_MAX_SIZE_KO", "Máximo 25 caracteres"],
  ["alumnograduacion", "nombre", "input", 27, "Búsqueda nombre válida", "SEARCH", true, "Subcadena válida"],

  ["alumnograduacion", "apellidos", "input", 28, "Apellidos requeridos", "ADD", "APELLIDOS_REQUIRED", "Apellidos obligatorios"],
  ["alumnograduacion", "apellidos", "input", 29, "Apellidos solo letras y espacios", "ADD", "APELLIDOS_FORMAT_KO", "Formato de apellidos inválido"],
  ["alumnograduacion", "apellidos", "input", 30, "Apellidos mínimo 2 caracteres", "ADD", "APELLIDOS_MIN_SIZE_KO", "Apellidos demasiado cortos"],
  ["alumnograduacion", "apellidos", "input", 31, "Apellidos máximo 35 caracteres", "ADD", "APELLIDOS_MAX_SIZE_KO", "Apellidos demasiado largos"],
  ["alumnograduacion", "apellidos", "input", 32, "Apellidos válidos", "ADD", true, "Apellidos correctos"],
  ["alumnograduacion", "apellidos", "input", 33, "Búsqueda apellidos vacía", "SEARCH", true, "Filtro opcional"],
  ["alumnograduacion", "apellidos", "input", 34, "Búsqueda apellidos formato", "SEARCH", "APELLIDOS_FORMAT_KO", "Solo letras en búsqueda"],
  ["alumnograduacion", "apellidos", "input", 35, "Búsqueda apellidos máximo", "SEARCH", "APELLIDOS_MAX_SIZE_KO", "Máximo 35 caracteres"],
  ["alumnograduacion", "apellidos", "input", 36, "Búsqueda apellidos válida", "SEARCH", true, "Subcadena válida"],

  ["alumnograduacion", "titulacion", "select", 37, "Titulación requerida", "ADD", "TITULACION_REQUIRED", "Debe seleccionar titulación"],
  ["alumnograduacion", "titulacion", "select", 38, "Titulación fuera de catálogo", "ADD", "TITULACION_ENUM_KO", "Valor no permitido"],
  ["alumnograduacion", "titulacion", "select", 39, "Titulación válida", "ADD", true, "Titulación correcta"],
  ["alumnograduacion", "titulacion", "select", 40, "Búsqueda titulaciones vacía", "SEARCH", true, "Filtro opcional"],
  ["alumnograduacion", "titulacion", "select", 41, "Búsqueda titulación inválida", "SEARCH", "TITULACION_ENUM_KO", "Valor no permitido"],
  ["alumnograduacion", "titulacion", "select", 42, "Búsqueda titulación válida", "SEARCH", true, "Valor permitido"],

  ["alumnograduacion", "dni", "input", 43, "DNI requerido", "ADD", "DNI_REQUIRED", "DNI obligatorio"],
  ["alumnograduacion", "dni", "input", 44, "DNI formato válido", "ADD", "DNI_FORMAT_KO", "Formato DNI/NIE incorrecto"],
  ["alumnograduacion", "dni", "input", 45, "DNI letra de control válida", "ADD", "DNI_LETTER_KO", "Letra de control incorrecta"],
  ["alumnograduacion", "dni", "input", 46, "DNI correcto", "ADD", true, "DNI válido"],
  ["alumnograduacion", "dni", "input", 47, "Búsqueda DNI vacía", "SEARCH", true, "Filtro opcional"],
  ["alumnograduacion", "dni", "input", 48, "Búsqueda DNI formato", "SEARCH", "DNI_FORMAT_KO", "Formato incorrecto en búsqueda"],
  ["alumnograduacion", "dni", "input", 49, "Búsqueda DNI válida", "SEARCH", true, "Filtro válido"],

  ["alumnograduacion", "telefono", "input", 50, "Teléfono requerido", "ADD", "TELEFONO_REQUIRED", "Teléfono obligatorio"],
  ["alumnograduacion", "telefono", "input", 51, "Teléfono 9 dígitos numéricos", "ADD", "TELEFONO_FORMAT_KO", "Debe contener 9 dígitos"],
  ["alumnograduacion", "telefono", "input", 52, "Teléfono válido", "ADD", true, "Teléfono correcto"],
  ["alumnograduacion", "telefono", "input", 53, "Búsqueda teléfono vacía", "SEARCH", true, "Filtro opcional"],
  ["alumnograduacion", "telefono", "input", 54, "Búsqueda teléfono formato", "SEARCH", "TELEFONO_FORMAT_KO", "Solo dígitos"],
  ["alumnograduacion", "telefono", "input", 55, "Búsqueda teléfono válida", "SEARCH", true, "Filtro válido"],

  ["alumnograduacion", "direccion", "input", 56, "Dirección requerida", "ADD", "DIRECCION_REQUIRED", "Dirección obligatoria"],
  ["alumnograduacion", "direccion", "input", 57, "Dirección formato permitido", "ADD", "DIRECCION_FORMAT_KO", "Solo caracteres permitidos"],
  ["alumnograduacion", "direccion", "input", 58, "Dirección máximo 150", "ADD", "DIRECCION_MAX_SIZE_KO", "Dirección demasiado larga"],
  ["alumnograduacion", "direccion", "input", 59, "Dirección válida", "ADD", true, "Dirección correcta"],
  ["alumnograduacion", "direccion", "input", 60, "Búsqueda dirección vacía", "SEARCH", true, "Filtro opcional"],
  ["alumnograduacion", "direccion", "input", 61, "Búsqueda dirección formato", "SEARCH", "DIRECCION_FORMAT_KO", "Caracteres no permitidos"],
  ["alumnograduacion", "direccion", "input", 62, "Búsqueda dirección máximo", "SEARCH", "DIRECCION_MAX_SIZE_KO", "Demasiados caracteres"],
  ["alumnograduacion", "direccion", "input", 63, "Búsqueda dirección válida", "SEARCH", true, "Subcadena válida"],

  ["alumnograduacion", "email", "input", 64, "Email requerido", "ADD", "EMAIL_REQUIRED", "Email obligatorio"],
  ["alumnograduacion", "email", "input", 65, "Email formato correcto", "ADD", "EMAIL_FORMAT_KO", "Formato de email incorrecto"],
  ["alumnograduacion", "email", "input", 66, "Email válido", "ADD", true, "Email correcto"],
  ["alumnograduacion", "email", "input", 67, "Búsqueda email vacía", "SEARCH", true, "Filtro opcional"],
  ["alumnograduacion", "email", "input", 68, "Búsqueda email formato", "SEARCH", "EMAIL_FORMAT_KO", "Formato de email incorrecto"],
  ["alumnograduacion", "email", "input", 69, "Búsqueda email válida", "SEARCH", true, "Filtro válido"],

  ["alumnograduacion", "nuevo_fotoacto", "file", 70, "Foto acto requerida", "ADD", "FOTOACTO_FILE_REQUIRED", "Debe adjuntar la foto"],
  ["alumnograduacion", "nuevo_fotoacto", "file", 71, "Tipo de archivo permitido", "ADD", "FOTOACTO_TYPE_KO", "Solo se acepta JPG/PNG"],
  ["alumnograduacion", "nuevo_fotoacto", "file", 72, "Tamaño máximo 2MB", "ADD", "FOTOACTO_MAX_SIZE_KO", "Foto demasiado grande"],
  ["alumnograduacion", "nuevo_fotoacto", "file", 73, "Nombre de archivo válido", "ADD", "FOTOACTO_NAME_KO", "Nombre no permitido"],
  ["alumnograduacion", "nuevo_fotoacto", "file", 74, "Foto acto válida", "ADD", true, "Archivo correcto"],

  ["alumnograduacion", "login", "input", 75, "Login requerido (EDIT)", "EDIT", "LOGIN_REQUIRED", "Login obligatorio"],
  ["alumnograduacion", "login", "input", 76, "Login mínimo 4 caracteres (EDIT)", "EDIT", "LOGIN_MIN_SIZE_KO", "Login demasiado corto"],
  ["alumnograduacion", "login", "input", 77, "Login máximo 15 caracteres (EDIT)", "EDIT", "LOGIN_MAX_SIZE_KO", "Login demasiado largo"],
  ["alumnograduacion", "login", "input", 78, "Login solo letras (EDIT)", "EDIT", "LOGIN_FORMAT_KO", "Solo letras sin espacios"],
  ["alumnograduacion", "login", "input", 79, "Login válido (EDIT)", "EDIT", true, "Login correcto"],

  ["alumnograduacion", "password", "input", 80, "Password requerida (EDIT)", "EDIT", "PASSWORD_REQUIRED", "Contraseña obligatoria"],
  ["alumnograduacion", "password", "input", 81, "Password mínima 8 caracteres (EDIT)", "EDIT", "PASSWORD_MIN_SIZE_KO", "Contraseña demasiado corta"],
  ["alumnograduacion", "password", "input", 82, "Password máxima 64 caracteres (EDIT)", "EDIT", "PASSWORD_MAX_SIZE_KO", "Contraseña demasiado larga"],
  ["alumnograduacion", "password", "input", 83, "Password sin símbolos (EDIT)", "EDIT", "PASSWORD_FORMAT_KO", "Sin símbolos"],
  ["alumnograduacion", "password", "input", 84, "Password válida (EDIT)", "EDIT", true, "Password correcta"],

  ["alumnograduacion", "nombre", "input", 85, "Nombre requerido (EDIT)", "EDIT", "NOMBRE_REQUIRED", "Nombre obligatorio"],
  ["alumnograduacion", "nombre", "input", 86, "Nombre solo letras y espacios (EDIT)", "EDIT", "NOMBRE_FORMAT_KO", "Formato de nombre inválido"],
  ["alumnograduacion", "nombre", "input", 87, "Nombre mínimo 2 caracteres (EDIT)", "EDIT", "NOMBRE_MIN_SIZE_KO", "Nombre demasiado corto"],
  ["alumnograduacion", "nombre", "input", 88, "Nombre máximo 25 caracteres (EDIT)", "EDIT", "NOMBRE_MAX_SIZE_KO", "Nombre demasiado largo"],
  ["alumnograduacion", "nombre", "input", 89, "Nombre válido (EDIT)", "EDIT", true, "Nombre correcto"],

  ["alumnograduacion", "apellidos", "input", 90, "Apellidos requeridos (EDIT)", "EDIT", "APELLIDOS_REQUIRED", "Apellidos obligatorios"],
  ["alumnograduacion", "apellidos", "input", 91, "Apellidos solo letras (EDIT)", "EDIT", "APELLIDOS_FORMAT_KO", "Formato inválido"],
  ["alumnograduacion", "apellidos", "input", 92, "Apellidos mínimo 2 caracteres (EDIT)", "EDIT", "APELLIDOS_MIN_SIZE_KO", "Demasiado corto"],
  ["alumnograduacion", "apellidos", "input", 93, "Apellidos máximo 35 caracteres (EDIT)", "EDIT", "APELLIDOS_MAX_SIZE_KO", "Demasiado largo"],
  ["alumnograduacion", "apellidos", "input", 94, "Apellidos válidos (EDIT)", "EDIT", true, "Apellidos correctos"],

  ["alumnograduacion", "titulacion", "select", 95, "Titulación requerida (EDIT)", "EDIT", "TITULACION_REQUIRED", "Debe seleccionar titulación"],
  ["alumnograduacion", "titulacion", "select", 96, "Titulación fuera de catálogo (EDIT)", "EDIT", "TITULACION_ENUM_KO", "Valor no permitido"],
  ["alumnograduacion", "titulacion", "select", 97, "Titulación válida (EDIT)", "EDIT", true, "Titulación correcta"],

  ["alumnograduacion", "dni", "input", 98, "DNI requerido (EDIT)", "EDIT", "DNI_REQUIRED", "DNI obligatorio"],
  ["alumnograduacion", "dni", "input", 99, "DNI formato válido (EDIT)", "EDIT", "DNI_FORMAT_KO", "Formato incorrecto"],
  ["alumnograduacion", "dni", "input", 100, "DNI letra control (EDIT)", "EDIT", "DNI_LETTER_KO", "Letra incorrecta"],
  ["alumnograduacion", "dni", "input", 101, "DNI válido (EDIT)", "EDIT", true, "DNI correcto"],

  ["alumnograduacion", "telefono", "input", 102, "Teléfono requerido (EDIT)", "EDIT", "TELEFONO_REQUIRED", "Teléfono obligatorio"],
  ["alumnograduacion", "telefono", "input", 103, "Teléfono formato 9 dígitos (EDIT)", "EDIT", "TELEFONO_FORMAT_KO", "Solo dígitos"],
  ["alumnograduacion", "telefono", "input", 104, "Teléfono válido (EDIT)", "EDIT", true, "Teléfono correcto"],

  ["alumnograduacion", "direccion", "input", 105, "Dirección requerida (EDIT)", "EDIT", "DIRECCION_REQUIRED", "Dirección obligatoria"],
  ["alumnograduacion", "direccion", "input", 106, "Dirección formato permitido (EDIT)", "EDIT", "DIRECCION_FORMAT_KO", "Caracteres no permitidos"],
  ["alumnograduacion", "direccion", "input", 107, "Dirección máximo 150 (EDIT)", "EDIT", "DIRECCION_MAX_SIZE_KO", "Demasiado larga"],
  ["alumnograduacion", "direccion", "input", 108, "Dirección válida (EDIT)", "EDIT", true, "Dirección correcta"],

  ["alumnograduacion", "email", "input", 109, "Email requerido (EDIT)", "EDIT", "EMAIL_REQUIRED", "Email obligatorio"],
  ["alumnograduacion", "email", "input", 110, "Email formato correcto (EDIT)", "EDIT", "EMAIL_FORMAT_KO", "Formato inválido"],
  ["alumnograduacion", "email", "input", 111, "Email válido (EDIT)", "EDIT", true, "Email correcto"],

  ["alumnograduacion", "nuevo_fotoacto", "file", 112, "Nombre archivo inválido (EDIT)", "EDIT", "FOTOACTO_NAME_KO", "Nombre no permitido"],
  ["alumnograduacion", "nuevo_fotoacto", "file", 113, "Tipo archivo inválido (EDIT)", "EDIT", "FOTOACTO_TYPE_KO", "Solo JPG"],
  ["alumnograduacion", "nuevo_fotoacto", "file", 114, "Tamaño archivo excedido (EDIT)", "EDIT", "FOTOACTO_MAX_SIZE_KO", "Foto demasiado grande"],
  ["alumnograduacion", "nuevo_fotoacto", "file", 115, "Foto válida (EDIT)", "EDIT", true, "Archivo correcto"],
];

var alumnograduacion_tests_fields = [
  ["alumnograduacion", "login", 1, 1, "ADD", [{ login: "" }], "LOGIN_REQUIRED"],
  ["alumnograduacion", "login", 2, 2, "ADD", [{ login: "abc" }], "LOGIN_MIN_SIZE_KO"],
  ["alumnograduacion", "login", 3, 3, "ADD", [{ login: "abcdefghijklmnop" }], "LOGIN_MAX_SIZE_KO"],
  ["alumnograduacion", "login", 4, 4, "ADD", [{ login: "Juan123" }], "LOGIN_FORMAT_KO"],
  ["alumnograduacion", "login", 5, 5, "ADD", [{ login: "Julio" }], true],
  ["alumnograduacion", "login", 6, 6, "SEARCH", [{ login: "" }], true],
  ["alumnograduacion", "login", 7, 7, "SEARCH", [{ login: "Ana99" }], "LOGIN_FORMAT_KO"],
  ["alumnograduacion", "login", 8, 8, "SEARCH", [{ login: "abcdefghijklmnop" }], "LOGIN_MAX_SIZE_KO"],
  ["alumnograduacion", "login", 9, 9, "SEARCH", [{ login: "Ana" }], true],

  ["alumnograduacion", "password", 10, 10, "ADD", [{ password: "" }], "PASSWORD_REQUIRED"],
  ["alumnograduacion", "password", 11, 11, "ADD", [{ password: "abc" }], "PASSWORD_MIN_SIZE_KO"],
  ["alumnograduacion", "password", 12, 12, "ADD", [{ password: "a".repeat(70) }], "PASSWORD_MAX_SIZE_KO"],
  ["alumnograduacion", "password", 13, 13, "ADD", [{ password: "pass$word" }], "PASSWORD_FORMAT_KO"],
  ["alumnograduacion", "password", 14, 14, "ADD", [{ password: "Password1" }], true],
  ["alumnograduacion", "password", 15, 15, "SEARCH", [{ password: "" }], true],
  ["alumnograduacion", "password", 16, 16, "SEARCH", [{ password: "clave$" }], "PASSWORD_FORMAT_KO"],
  ["alumnograduacion", "password", 17, 17, "SEARCH", [{ password: "a".repeat(70) }], "PASSWORD_MAX_SIZE_KO"],
  ["alumnograduacion", "password", 18, 18, "SEARCH", [{ password: "Clave" }], true],

  ["alumnograduacion", "nombre", 19, 19, "ADD", [{ nombre: "" }], "NOMBRE_REQUIRED"],
  ["alumnograduacion", "nombre", 20, 20, "ADD", [{ nombre: "Juan2" }], "NOMBRE_FORMAT_KO"],
  ["alumnograduacion", "nombre", 21, 21, "ADD", [{ nombre: "J" }], "NOMBRE_MIN_SIZE_KO"],
  ["alumnograduacion", "nombre", 22, 22, "ADD", [{ nombre: "A".repeat(26) }], "NOMBRE_MAX_SIZE_KO"],
  ["alumnograduacion", "nombre", 23, 23, "ADD", [{ nombre: "Juan" }], true],
  ["alumnograduacion", "nombre", 24, 24, "SEARCH", [{ nombre: "" }], true],
  ["alumnograduacion", "nombre", 25, 25, "SEARCH", [{ nombre: "Lu2" }], "NOMBRE_FORMAT_KO"],
  ["alumnograduacion", "nombre", 26, 26, "SEARCH", [{ nombre: "A".repeat(30) }], "NOMBRE_MAX_SIZE_KO"],
  ["alumnograduacion", "nombre", 27, 27, "SEARCH", [{ nombre: "Lu" }], true],

  ["alumnograduacion", "apellidos", 28, 28, "ADD", [{ apellidos: "" }], "APELLIDOS_REQUIRED"],
  ["alumnograduacion", "apellidos", 29, 29, "ADD", [{ apellidos: "Pérez3" }], "APELLIDOS_FORMAT_KO"],
  ["alumnograduacion", "apellidos", 30, 30, "ADD", [{ apellidos: "A" }], "APELLIDOS_MIN_SIZE_KO"],
  ["alumnograduacion", "apellidos", 31, 31, "ADD", [{ apellidos: "Apellido".repeat(6) }], "APELLIDOS_MAX_SIZE_KO"],
  ["alumnograduacion", "apellidos", 32, 32, "ADD", [{ apellidos: "Pérez Gómez" }], true],
  ["alumnograduacion", "apellidos", 33, 33, "SEARCH", [{ apellidos: "" }], true],
  ["alumnograduacion", "apellidos", 34, 34, "SEARCH", [{ apellidos: "Gómez1" }], "APELLIDOS_FORMAT_KO"],
  ["alumnograduacion", "apellidos", 35, 35, "SEARCH", [{ apellidos: "Apellido".repeat(6) }], "APELLIDOS_MAX_SIZE_KO"],
  ["alumnograduacion", "apellidos", 36, 36, "SEARCH", [{ apellidos: "Gómez" }], true],

  ["alumnograduacion", "titulacion", 37, 37, "ADD", [{ titulacion: "" }], "TITULACION_REQUIRED"],
  ["alumnograduacion", "titulacion", 38, 38, "ADD", [{ titulacion: "OTRA" }], "TITULACION_ENUM_KO"],
  ["alumnograduacion", "titulacion", 39, 39, "ADD", [{ titulacion: "GREI" }], true],
  ["alumnograduacion", "titulacion", 40, 40, "SEARCH", [{ titulacion: "" }], true],
  ["alumnograduacion", "titulacion", 41, 41, "SEARCH", [{ titulacion: "OTRA" }], "TITULACION_ENUM_KO"],
  ["alumnograduacion", "titulacion", 42, 42, "SEARCH", [{ titulacion: "GRIA" }], true],

  ["alumnograduacion", "dni", 43, 43, "ADD", [{ dni: "" }], "DNI_REQUIRED"],
  ["alumnograduacion", "dni", 44, 44, "ADD", [{ dni: "1234A" }], "DNI_FORMAT_KO"],
  ["alumnograduacion", "dni", 45, 45, "ADD", [{ dni: "12345678A" }], "DNI_LETTER_KO"],
  ["alumnograduacion", "dni", 46, 46, "ADD", [{ dni: "12345678Z" }], true],
  ["alumnograduacion", "dni", 47, 47, "SEARCH", [{ dni: "" }], true],
  ["alumnograduacion", "dni", 48, 48, "SEARCH", [{ dni: "12A" }], "DNI_FORMAT_KO"],
  ["alumnograduacion", "dni", 49, 49, "SEARCH", [{ dni: "12345678Z" }], true],

  ["alumnograduacion", "telefono", 50, 50, "ADD", [{ telefono: "" }], "TELEFONO_REQUIRED"],
  ["alumnograduacion", "telefono", 51, 51, "ADD", [{ telefono: "54A3210B9" }], "TELEFONO_FORMAT_KO"],
  ["alumnograduacion", "telefono", 52, 52, "ADD", [{ telefono: "654321098" }], true],
  ["alumnograduacion", "telefono", 53, 53, "SEARCH", [{ telefono: "" }], true],
  ["alumnograduacion", "telefono", 54, 54, "SEARCH", [{ telefono: "1234abc" }], "TELEFONO_FORMAT_KO"],
  ["alumnograduacion", "telefono", 55, 55, "SEARCH", [{ telefono: "654321098" }], true],

  ["alumnograduacion", "direccion", 56, 56, "ADD", [{ direccion: "" }], "DIRECCION_REQUIRED"],
  ["alumnograduacion", "direccion", 57, 57, "ADD", [{ direccion: "Calle+1" }], "DIRECCION_FORMAT_KO"],
  ["alumnograduacion", "direccion", 58, 58, "ADD", [{ direccion: "C".repeat(160) }], "DIRECCION_MAX_SIZE_KO"],
  ["alumnograduacion", "direccion", 59, 59, "ADD", [{ direccion: "Calle Mayor 10" }], true],
  ["alumnograduacion", "direccion", 60, 60, "SEARCH", [{ direccion: "" }], true],
  ["alumnograduacion", "direccion", 61, 61, "SEARCH", [{ direccion: "Calle+1" }], "DIRECCION_FORMAT_KO"],
  ["alumnograduacion", "direccion", 62, 62, "SEARCH", [{ direccion: "C".repeat(160) }], "DIRECCION_MAX_SIZE_KO"],
  ["alumnograduacion", "direccion", 63, 63, "SEARCH", [{ direccion: "Calle" }], true],

  ["alumnograduacion", "email", 64, 64, "ADD", [{ email: "" }], "EMAIL_REQUIRED"],
  ["alumnograduacion", "email", 65, 65, "ADD", [{ email: "correo@" }], "EMAIL_FORMAT_KO"],
  ["alumnograduacion", "email", 66, 66, "ADD", [{ email: "correo@example.com" }], true],
  ["alumnograduacion", "email", 67, 67, "SEARCH", [{ email: "" }], true],
  ["alumnograduacion", "email", 68, 68, "SEARCH", [{ email: "correo@" }], "EMAIL_FORMAT_KO"],
  ["alumnograduacion", "email", 69, 69, "SEARCH", [{ email: "correo@example.com" }], true],

  ["alumnograduacion", "login", 75, 70, "EDIT", [{ login: "" }], "LOGIN_REQUIRED"],
  ["alumnograduacion", "login", 76, 71, "EDIT", [{ login: "abc" }], "LOGIN_MIN_SIZE_KO"],
  ["alumnograduacion", "login", 77, 72, "EDIT", [{ login: "abcdefghijklmnop" }], "LOGIN_MAX_SIZE_KO"],
  ["alumnograduacion", "login", 78, 73, "EDIT", [{ login: "Juan123" }], "LOGIN_FORMAT_KO"],
  ["alumnograduacion", "login", 79, 74, "EDIT", [{ login: "Julio" }], true],

  ["alumnograduacion", "password", 80, 75, "EDIT", [{ password: "" }], "PASSWORD_REQUIRED"],
  ["alumnograduacion", "password", 81, 76, "EDIT", [{ password: "abc" }], "PASSWORD_MIN_SIZE_KO"],
  ["alumnograduacion", "password", 82, 77, "EDIT", [{ password: "a".repeat(70) }], "PASSWORD_MAX_SIZE_KO"],
  ["alumnograduacion", "password", 83, 78, "EDIT", [{ password: "pass$word" }], "PASSWORD_FORMAT_KO"],
  ["alumnograduacion", "password", 84, 79, "EDIT", [{ password: "Password1" }], true],

  ["alumnograduacion", "nombre", 85, 80, "EDIT", [{ nombre: "" }], "NOMBRE_REQUIRED"],
  ["alumnograduacion", "nombre", 86, 81, "EDIT", [{ nombre: "Juan2" }], "NOMBRE_FORMAT_KO"],
  ["alumnograduacion", "nombre", 87, 82, "EDIT", [{ nombre: "J" }], "NOMBRE_MIN_SIZE_KO"],
  ["alumnograduacion", "nombre", 88, 83, "EDIT", [{ nombre: "A".repeat(26) }], "NOMBRE_MAX_SIZE_KO"],
  ["alumnograduacion", "nombre", 89, 84, "EDIT", [{ nombre: "Juan" }], true],

  ["alumnograduacion", "apellidos", 90, 85, "EDIT", [{ apellidos: "" }], "APELLIDOS_REQUIRED"],
  ["alumnograduacion", "apellidos", 91, 86, "EDIT", [{ apellidos: "Pérez3" }], "APELLIDOS_FORMAT_KO"],
  ["alumnograduacion", "apellidos", 92, 87, "EDIT", [{ apellidos: "A" }], "APELLIDOS_MIN_SIZE_KO"],
  ["alumnograduacion", "apellidos", 93, 88, "EDIT", [{ apellidos: "Apellido".repeat(6) }], "APELLIDOS_MAX_SIZE_KO"],
  ["alumnograduacion", "apellidos", 94, 89, "EDIT", [{ apellidos: "Pérez Gómez" }], true],

  ["alumnograduacion", "titulacion", 95, 90, "EDIT", [{ titulacion: "" }], "TITULACION_REQUIRED"],
  ["alumnograduacion", "titulacion", 96, 91, "EDIT", [{ titulacion: "OTRA" }], "TITULACION_ENUM_KO"],
  ["alumnograduacion", "titulacion", 97, 92, "EDIT", [{ titulacion: "GREI" }], true],

  ["alumnograduacion", "dni", 98, 93, "EDIT", [{ dni: "" }], "DNI_REQUIRED"],
  ["alumnograduacion", "dni", 99, 94, "EDIT", [{ dni: "1234A" }], "DNI_FORMAT_KO"],
  ["alumnograduacion", "dni", 100, 95, "EDIT", [{ dni: "12345678A" }], "DNI_LETTER_KO"],
  ["alumnograduacion", "dni", 101, 96, "EDIT", [{ dni: "12345678Z" }], true],

  ["alumnograduacion", "telefono", 102, 97, "EDIT", [{ telefono: "" }], "TELEFONO_REQUIRED"],
  ["alumnograduacion", "telefono", 103, 98, "EDIT", [{ telefono: "54A3210B9" }], "TELEFONO_FORMAT_KO"],
  ["alumnograduacion", "telefono", 104, 99, "EDIT", [{ telefono: "654321098" }], true],

  ["alumnograduacion", "direccion", 105, 100, "EDIT", [{ direccion: "" }], "DIRECCION_REQUIRED"],
  ["alumnograduacion", "direccion", 106, 101, "EDIT", [{ direccion: "Calle+1" }], "DIRECCION_FORMAT_KO"],
  ["alumnograduacion", "direccion", 107, 102, "EDIT", [{ direccion: "C".repeat(160) }], "DIRECCION_MAX_SIZE_KO"],
  ["alumnograduacion", "direccion", 108, 103, "EDIT", [{ direccion: "Calle Mayor 10" }], true],

  ["alumnograduacion", "email", 109, 104, "EDIT", [{ email: "" }], "EMAIL_REQUIRED"],
  ["alumnograduacion", "email", 110, 105, "EDIT", [{ email: "correo@" }], "EMAIL_FORMAT_KO"],
  ["alumnograduacion", "email", 111, 106, "EDIT", [{ email: "correo@example.com" }], true],
];

var alumnograduacion_tests_files = [
  ["alumnograduacion", "nuevo_fotoacto", 70, 1, "ADD", "", [], "FOTOACTO_FILE_REQUIRED"],
  [
    "alumnograduacion",
    "nuevo_fotoacto",
    71,
    2,
    "ADD",
    "",
    [
      { format_name_file: "acto.jpg" },
      { type_file: "image/gif" },
      { max_size_file: 500000 },
    ],
    "FOTOACTO_TYPE_KO",
  ],
  [
    "alumnograduacion",
    "nuevo_fotoacto",
    72,
    3,
    "ADD",
    "",
    [
      { format_name_file: "acto.jpg" },
      { type_file: "image/jpeg" },
      { max_size_file: 4000000 },
    ],
    "FOTOACTO_MAX_SIZE_KO",
  ],
  [
    "alumnograduacion",
    "nuevo_fotoacto",
    73,
    4,
    "ADD",
    "",
    [
      { format_name_file: "acto final.jpg" },
      { type_file: "image/jpeg" },
      { max_size_file: 500000 },
    ],
    "FOTOACTO_NAME_KO",
  ],
  [
    "alumnograduacion",
    "nuevo_fotoacto",
    74,
    5,
    "ADD",
    "",
    [
      { format_name_file: "acto.jpg" },
      { type_file: "image/jpeg" },
      { max_size_file: 500000 },
    ],
    true,
  ],
  [
    "alumnograduacion",
    "nuevo_fotoacto",
    112,
    6,
    "EDIT",
    "",
    [
      { format_name_file: "acto final.jpg" },
      { type_file: "image/jpeg" },
      { max_size_file: 500000 },
    ],
    "FOTOACTO_NAME_KO",
  ],
  [
    "alumnograduacion",
    "nuevo_fotoacto",
    113,
    7,
    "EDIT",
    "",
    [
      { format_name_file: "acto.jpg" },
      { type_file: "image/gif" },
      { max_size_file: 500000 },
    ],
    "FOTOACTO_TYPE_KO",
  ],
  [
    "alumnograduacion",
    "nuevo_fotoacto",
    114,
    8,
    "EDIT",
    "",
    [
      { format_name_file: "acto.jpg" },
      { type_file: "image/jpeg" },
      { max_size_file: 4000000 },
    ],
    "FOTOACTO_MAX_SIZE_KO",
  ],
  [
    "alumnograduacion",
    "nuevo_fotoacto",
    115,
    9,
    "EDIT",
    "",
    [
      { format_name_file: "acto.jpg" },
      { type_file: "image/jpeg" },
      { max_size_file: 500000 },
    ],
    true,
  ],
];
