var textos_ES = {
  text_titulo_app: "Gestión ET2",
  text_titulo_menu: "Menú",
  menu_articulo: "Artículos",
  menu_ubicacion: "Ubicaciones",
  menu_alumnograduacion: "Alumnado graduación",
  text_titulo_page_articulo: "Gestión de artículos",
  text_titulo_page_ubicacion: "Gestión de ubicaciones",
  text_titulo_page_alumnograduacion: "Gestión de alumnado graduación",

  text_form_articulo_ADD: "Añadir artículo",
  text_form_articulo_SEARCH: "Buscar artículos",
  text_form_articulo_EDIT: "Editar artículo",
  text_form_articulo_DELETE: "Eliminar artículo",
  text_form_articulo_SHOWCURRENT: "Detalle de artículo",

  text_form_ubicacion_ADD: "Añadir ubicación",
  text_form_ubicacion_SEARCH: "Buscar ubicaciones",
  text_form_ubicacion_EDIT: "Editar ubicación",
  text_form_ubicacion_DELETE: "Eliminar ubicación",
  text_form_ubicacion_SHOWCURRENT: "Detalle de ubicación",

  text_form_alumnograduacion_ADD: "Añadir alumno",
  text_form_alumnograduacion_SEARCH: "Buscar alumnado",
  text_form_alumnograduacion_EDIT: "Editar alumno",
  text_form_alumnograduacion_DELETE: "Eliminar alumno",
  text_form_alumnograduacion_SHOWCURRENT: "Detalle de alumno",

  label_CodigoA: "Código",
  label_AutoresA: "Autores",
  label_TituloA: "Título del artículo",
  label_TituloR: "Título de la revista",
  label_ISSN: "ISSN",
  label_VolumenR: "Volumen",
  label_PagIniA: "Página inicial",
  label_PagFinA: "Página final",
  label_FechaPublicacionR: "Fecha de publicación",
  label_EstadoA: "Estado",
  EstadoA_Enviado: "Enviado",
  EstadoA_Revision: "Revisión",
  EstadoA_Publicado: "Publicado",
  label_FicheropdfA: "Fichero PDF existente",
  label_nuevo_FicheropdfA: "Nuevo PDF",

  label_id_site: "Identificador",
  label_site_latitud: "Latitud (WGS84)",
  label_site_longitud: "Longitud (WGS84)",
  label_site_altitude: "Altitud",
  label_site_locality: "Localidad",
  label_site_provider_login: "Login proveedor",
  label_site_north_photo: "Foto Norte",
  label_nuevo_site_north_photo: "Nueva foto Norte",
  label_site_south_photo: "Foto Sur",
  label_nuevo_site_south_photo: "Nueva foto Sur",
  label_site_east_photo: "Foto Este",
  label_nuevo_site_east_photo: "Nueva foto Este",
  label_site_west_photo: "Foto Oeste",
  label_nuevo_site_west_photo: "Nueva foto Oeste",

  label_login: "Login",
  label_password: "Contraseña",
  label_nombre: "Nombre",
  label_apellidos: "Apellidos",
  label_titulacion: "Titulación",
  titulacion_placeholder: "Seleccione titulación",
  titulacion_GREI: "GREI",
  titulacion_GRIA: "GRIA",
  titulacion_MEI: "MEI",
  titulacion_MIA: "MIA",
  titulacion_PCEO: "PCEO",
  label_dni: "DNI/NIE",
  label_telefono: "Teléfono",
  label_direccion: "Dirección",
  label_email: "Correo electrónico",
  label_fotoacto: "Foto acto existente",
  label_nuevo_fotoacto: "Nueva foto acto",

  icon_file: "Abrir fichero",

  CODIGOA_REQUIRED: "El código es obligatorio.",
  CODIGOA_MIN_SIZE_KO: "El código debe tener al menos 1 dígito.",
  CODIGOA_MAX_SIZE_KO: "El código no puede superar 11 dígitos.",
  CODIGOA_FORMAT_KO: "El código solo admite dígitos.",
  AUTORESA_REQUIRED: "Los autores son obligatorios.",
  AUTORESA_MIN_SIZE_KO: "Debe indicar al menos un autor.",
  AUTORESA_MAX_SIZE_KO: "Los autores no pueden superar 200 caracteres.",
  AUTORESA_FORMAT_KO: "Los autores solo admiten letras y puntuación básica.",
  TITULOA_REQUIRED: "El título del artículo es obligatorio.",
  TITULOA_MIN_SIZE_KO: "El título debe tener contenido.",
  TITULOA_MAX_SIZE_KO: "El título no puede superar 100 caracteres.",
  TITULOA_FORMAT_KO: "El título incluye caracteres no permitidos.",
  TITULOR_REQUIRED: "El título de la revista es obligatorio.",
  TITULOR_MIN_SIZE_KO: "El título de revista debe tener contenido.",
  TITULOR_MAX_SIZE_KO: "El título de revista no puede superar 100 caracteres.",
  TITULOR_FORMAT_KO: "El título de revista incluye caracteres no permitidos.",
  ISSN_REQUIRED: "Debe indicar el ISSN.",
  ISSN_FORMAT_KO: "El ISSN debe seguir el patrón ####-###X.",
  VOLUMENR_REQUIRED: "Debe indicar el volumen.",
  VOLUMENR_FORMAT_KO: "El volumen solo admite números (1-4 dígitos).",
  PAGINIA_REQUIRED: "Debe indicar la página inicial.",
  PAGINIA_FORMAT_KO: "La página inicial solo admite números.",
  PAGFINA_REQUIRED: "Debe indicar la página final.",
  PAGFINA_FORMAT_KO: "La página final solo admite números.",
  PAGFINA_RANGE_KO: "La página final debe ser mayor o igual que la inicial.",
  FECHAPUBLICACIONR_REQUIRED: "Debe indicar la fecha de publicación.",
  FECHAPUBLICACIONR_FORMAT_KO: "La fecha debe seguir el formato AAAA-MM-DD.",
  FECHAPUBLICACIONR_FUTURE_KO: "La fecha no puede ser posterior a hoy.",
  ESTADOA_REQUIRED: "Debe seleccionar un estado.",
  ESTADOA_ENUM_KO: "El estado indicado no es válido.",
  FICHEROPDFA_FILE_REQUIRED: "Debe adjuntar el PDF del artículo.",
  FICHEROPDFA_MAX_SIZE_KO: "El PDF supera el tamaño máximo permitido.",
  FICHEROPDFA_TYPE_KO: "El fichero debe ser un PDF.",
  FICHEROPDFA_NAME_KO: "El nombre del PDF contiene caracteres no permitidos.",

  IDSITE_REQUIRED: "Debe indicar el identificador de sitio.",
  IDSITE_FORMAT_KO: "El identificador solo admite números.",
  LATITUD_REQUIRED: "Debe indicar la latitud.",
  LATITUD_FORMAT_KO: "La latitud debe tener formato decimal con punto.",
  LATITUD_RANGE_KO: "La latitud debe estar entre -90 y 90.",
  LONGITUD_REQUIRED: "Debe indicar la longitud.",
  LONGITUD_FORMAT_KO: "La longitud debe tener formato decimal con punto.",
  LONGITUD_RANGE_KO: "La longitud debe estar entre -180 y 180.",
  ALTITUDE_REQUIRED: "Debe indicar la altitud.",
  ALTITUDE_FORMAT_KO: "La altitud solo admite números (puede ser negativa).",
  LOCALITY_REQUIRED: "Debe indicar la localidad.",
  LOCALITY_MAX_SIZE_KO: "La localidad no puede superar 40 caracteres.",
  LOCALITY_FORMAT_KO: "La localidad contiene caracteres no permitidos.",
  PROVIDER_REQUIRED: "Debe indicar el login del proveedor.",
  PROVIDER_MAX_SIZE_KO: "El login no puede superar 30 caracteres.",
  PROVIDER_FORMAT_KO: "El login solo admite letras, números y ._-",
  SITE_NORTH_PHOTO_FILE_REQUIRED: "Debe adjuntar la foto norte.",
  SITE_NORTH_PHOTO_MAX_SIZE_KO: "La foto norte supera el tamaño máximo.",
  SITE_NORTH_PHOTO_TYPE_KO: "La foto norte debe ser JPG o PNG.",
  SITE_NORTH_PHOTO_NAME_KO: "El nombre de la foto norte contiene caracteres no permitidos.",
  SITE_SOUTH_PHOTO_FILE_REQUIRED: "Debe adjuntar la foto sur.",
  SITE_SOUTH_PHOTO_MAX_SIZE_KO: "La foto sur supera el tamaño máximo.",
  SITE_SOUTH_PHOTO_TYPE_KO: "La foto sur debe ser JPG o PNG.",
  SITE_SOUTH_PHOTO_NAME_KO: "El nombre de la foto sur contiene caracteres no permitidos.",
  SITE_EAST_PHOTO_FILE_REQUIRED: "Debe adjuntar la foto este.",
  SITE_EAST_PHOTO_MAX_SIZE_KO: "La foto este supera el tamaño máximo.",
  SITE_EAST_PHOTO_TYPE_KO: "La foto este debe ser JPG o PNG.",
  SITE_EAST_PHOTO_NAME_KO: "El nombre de la foto este contiene caracteres no permitidos.",
  SITE_WEST_PHOTO_FILE_REQUIRED: "Debe adjuntar la foto oeste.",
  SITE_WEST_PHOTO_MAX_SIZE_KO: "La foto oeste supera el tamaño máximo.",
  SITE_WEST_PHOTO_TYPE_KO: "La foto oeste debe ser JPG o PNG.",
  SITE_WEST_PHOTO_NAME_KO: "El nombre de la foto oeste contiene caracteres no permitidos.",
  NUEVO_SITE_NORTH_PHOTO_MAX_SIZE_KO: "La nueva foto norte supera el tamaño máximo.",
  NUEVO_SITE_NORTH_PHOTO_TYPE_KO: "La nueva foto norte debe ser JPG o PNG.",
  NUEVO_SITE_NORTH_PHOTO_NAME_KO: "El nombre de la nueva foto norte es inválido.",
  NUEVO_SITE_SOUTH_PHOTO_MAX_SIZE_KO: "La nueva foto sur supera el tamaño máximo.",
  NUEVO_SITE_SOUTH_PHOTO_TYPE_KO: "La nueva foto sur debe ser JPG o PNG.",
  NUEVO_SITE_SOUTH_PHOTO_NAME_KO: "El nombre de la nueva foto sur es inválido.",
  NUEVO_SITE_EAST_PHOTO_MAX_SIZE_KO: "La nueva foto este supera el tamaño máximo.",
  NUEVO_SITE_EAST_PHOTO_TYPE_KO: "La nueva foto este debe ser JPG o PNG.",
  NUEVO_SITE_EAST_PHOTO_NAME_KO: "El nombre de la nueva foto este es inválido.",
  NUEVO_SITE_WEST_PHOTO_MAX_SIZE_KO: "La nueva foto oeste supera el tamaño máximo.",
  NUEVO_SITE_WEST_PHOTO_TYPE_KO: "La nueva foto oeste debe ser JPG o PNG.",
  NUEVO_SITE_WEST_PHOTO_NAME_KO: "El nombre de la nueva foto oeste es inválido.",

  LOGIN_REQUIRED: "Debe indicar el login.",
  LOGIN_MIN_SIZE_KO: "El login debe tener al menos 4 caracteres.",
  LOGIN_MAX_SIZE_KO: "El login no puede superar 15 caracteres.",
  LOGIN_FORMAT_KO: "El login solo admite letras sin espacios.",
  PASSWORD_REQUIRED: "Debe indicar la contraseña.",
  PASSWORD_MIN_SIZE_KO: "La contraseña debe tener al menos 8 caracteres.",
  PASSWORD_MAX_SIZE_KO: "La contraseña no puede superar 64 caracteres.",
  PASSWORD_FORMAT_KO: "La contraseña solo admite letras y números.",
  NOMBRE_REQUIRED: "Debe indicar el nombre.",
  NOMBRE_MIN_SIZE_KO: "El nombre debe tener al menos 2 caracteres.",
  NOMBRE_MAX_SIZE_KO: "El nombre no puede superar 25 caracteres.",
  NOMBRE_FORMAT_KO: "El nombre solo admite letras y espacios.",
  APELLIDOS_REQUIRED: "Debe indicar los apellidos.",
  APELLIDOS_MIN_SIZE_KO: "Los apellidos deben tener al menos 2 caracteres.",
  APELLIDOS_MAX_SIZE_KO: "Los apellidos no pueden superar 35 caracteres.",
  APELLIDOS_FORMAT_KO: "Los apellidos solo admiten letras y espacios.",
  TITULACION_REQUIRED: "Debe seleccionar una titulación.",
  TITULACION_ENUM_KO: "La titulación indicada no es válida.",
  DNI_REQUIRED: "Debe indicar el DNI/NIE.",
  DNI_FORMAT_KO: "El DNI/NIE tiene un formato inválido.",
  DNI_LETTER_KO: "La letra del DNI/NIE no es correcta.",
  TELEFONO_REQUIRED: "Debe indicar el teléfono.",
  TELEFONO_FORMAT_KO: "El teléfono debe tener 9 dígitos.",
  DIRECCION_REQUIRED: "Debe indicar la dirección.",
  DIRECCION_MAX_SIZE_KO: "La dirección no puede superar 150 caracteres.",
  DIRECCION_FORMAT_KO: "La dirección contiene caracteres no permitidos.",
  EMAIL_REQUIRED: "Debe indicar el correo electrónico.",
  EMAIL_FORMAT_KO: "El correo electrónico no tiene un formato válido.",
  FOTOACTO_FILE_REQUIRED: "Debe adjuntar la foto del acto.",
  FOTOACTO_MAX_SIZE_KO: "La foto supera el tamaño máximo permitido.",
  FOTOACTO_TYPE_KO: "La foto debe estar en formato JPG.",
  FOTOACTO_NAME_KO: "El nombre de la foto contiene caracteres no permitidos.",
  NUEVO_FOTOACTO_MAX_SIZE_KO: "La nueva foto supera el tamaño máximo.",
  NUEVO_FOTOACTO_TYPE_KO: "La nueva foto debe ser JPG o PNG.",
  NUEVO_FOTOACTO_NAME_KO: "El nombre de la nueva foto contiene caracteres no permitidos.",
};
