var textos_EN = {
  text_titulo_app: "ET2 Management",
  text_titulo_menu: "Menu",
  menu_articulo: "Articles",
  menu_ubicacion: "Sites",
  menu_alumnograduacion: "Graduates",
  text_titulo_page_articulo: "Article management",
  text_titulo_page_ubicacion: "Site management",
  text_titulo_page_alumnograduacion: "Graduate management",

  text_form_articulo_ADD: "Add article",
  text_form_articulo_SEARCH: "Search articles",
  text_form_articulo_EDIT: "Edit article",
  text_form_articulo_DELETE: "Delete article",
  text_form_articulo_SHOWCURRENT: "Article details",

  text_form_ubicacion_ADD: "Add site",
  text_form_ubicacion_SEARCH: "Search sites",
  text_form_ubicacion_EDIT: "Edit site",
  text_form_ubicacion_DELETE: "Delete site",
  text_form_ubicacion_SHOWCURRENT: "Site details",

  text_form_alumnograduacion_ADD: "Add student",
  text_form_alumnograduacion_SEARCH: "Search students",
  text_form_alumnograduacion_EDIT: "Edit student",
  text_form_alumnograduacion_DELETE: "Delete student",
  text_form_alumnograduacion_SHOWCURRENT: "Student details",

  label_CodigoA: "Code",
  label_AutoresA: "Authors",
  label_TituloA: "Article title",
  label_TituloR: "Journal title",
  label_ISSN: "ISSN",
  label_VolumenR: "Volume",
  label_PagIniA: "Start page",
  label_PagFinA: "End page",
  label_FechaPublicacionR: "Publication date",
  label_EstadoA: "Status",
  EstadoA_Enviado: "Submitted",
  EstadoA_Revision: "Review",
  EstadoA_Publicado: "Published",
  label_FicheropdfA: "Current PDF",
  label_nuevo_FicheropdfA: "New PDF",

  label_id_site: "Identifier",
  label_site_latitud: "Latitude (WGS84)",
  label_site_longitud: "Longitude (WGS84)",
  label_site_altitude: "Altitude",
  label_site_locality: "Locality",
  label_site_provider_login: "Provider login",
  label_site_north_photo: "North photo",
  label_nuevo_site_north_photo: "New north photo",
  label_site_south_photo: "South photo",
  label_nuevo_site_south_photo: "New south photo",
  label_site_east_photo: "East photo",
  label_nuevo_site_east_photo: "New east photo",
  label_site_west_photo: "West photo",
  label_nuevo_site_west_photo: "New west photo",

  label_login: "Login",
  label_password: "Password",
  label_nombre: "Name",
  label_apellidos: "Surname",
  label_titulacion: "Degree",
  titulacion_placeholder: "Select degree",
  titulacion_GREI: "GREI",
  titulacion_GRIA: "GRIA",
  titulacion_MEI: "MEI",
  titulacion_MIA: "MIA",
  titulacion_PCEO: "PCEO",
  label_dni: "National ID",
  label_telefono: "Phone",
  label_direccion: "Address",
  label_email: "Email",
  label_fotoacto: "Current ceremony photo",
  label_nuevo_fotoacto: "New ceremony photo",

  icon_file: "Open file",

  CODIGOA_REQUIRED: "Code is required.",
  CODIGOA_MIN_SIZE_KO: "Code must contain at least 1 digit.",
  CODIGOA_MAX_SIZE_KO: "Code cannot exceed 11 digits.",
  CODIGOA_FORMAT_KO: "Code only accepts digits.",
  AUTORESA_REQUIRED: "Authors are required.",
  AUTORESA_MIN_SIZE_KO: "Provide at least one author.",
  AUTORESA_MAX_SIZE_KO: "Authors cannot exceed 200 characters.",
  AUTORESA_FORMAT_KO: "Authors only allow letters and common punctuation.",
  TITULOA_REQUIRED: "Article title is required.",
  TITULOA_MIN_SIZE_KO: "Article title must have content.",
  TITULOA_MAX_SIZE_KO: "Article title cannot exceed 100 characters.",
  TITULOA_FORMAT_KO: "Article title includes invalid characters.",
  TITULOR_REQUIRED: "Journal title is required.",
  TITULOR_MIN_SIZE_KO: "Journal title must have content.",
  TITULOR_MAX_SIZE_KO: "Journal title cannot exceed 100 characters.",
  TITULOR_FORMAT_KO: "Journal title includes invalid characters.",
  ISSN_REQUIRED: "ISSN is required.",
  ISSN_FORMAT_KO: "ISSN must match pattern ####-###X.",
  VOLUMENR_REQUIRED: "Volume is required.",
  VOLUMENR_FORMAT_KO: "Volume only accepts numbers (1-4 digits).",
  PAGINIA_REQUIRED: "Start page is required.",
  PAGINIA_FORMAT_KO: "Start page only accepts digits.",
  PAGFINA_REQUIRED: "End page is required.",
  PAGFINA_FORMAT_KO: "End page only accepts digits.",
  PAGFINA_RANGE_KO: "End page must be greater than or equal to start page.",
  FECHAPUBLICACIONR_REQUIRED: "Publication date is required.",
  FECHAPUBLICACIONR_FORMAT_KO: "Date must follow YYYY-MM-DD.",
  FECHAPUBLICACIONR_FUTURE_KO: "Date cannot be later than today.",
  ESTADOA_REQUIRED: "Status is required.",
  ESTADOA_ENUM_KO: "The selected status is invalid.",
  FICHEROPDFA_FILE_REQUIRED: "Attach the article PDF.",
  FICHEROPDFA_MAX_SIZE_KO: "PDF exceeds the maximum allowed size.",
  FICHEROPDFA_TYPE_KO: "File must be a PDF.",
  FICHEROPDFA_NAME_KO: "PDF name contains invalid characters.",

  IDSITE_REQUIRED: "Site identifier is required.",
  IDSITE_FORMAT_KO: "Site identifier only accepts digits.",
  LATITUD_REQUIRED: "Latitude is required.",
  LATITUD_FORMAT_KO: "Latitude must be a decimal number.",
  LATITUD_RANGE_KO: "Latitude must be between -90 and 90.",
  LONGITUD_REQUIRED: "Longitude is required.",
  LONGITUD_FORMAT_KO: "Longitude must be a decimal number.",
  LONGITUD_RANGE_KO: "Longitude must be between -180 and 180.",
  ALTITUDE_REQUIRED: "Altitude is required.",
  ALTITUDE_FORMAT_KO: "Altitude only accepts digits (optional sign).",
  LOCALITY_REQUIRED: "Locality is required.",
  LOCALITY_MAX_SIZE_KO: "Locality cannot exceed 40 characters.",
  LOCALITY_FORMAT_KO: "Locality contains invalid characters.",
  PROVIDER_REQUIRED: "Provider login is required.",
  PROVIDER_MAX_SIZE_KO: "Provider login cannot exceed 30 characters.",
  PROVIDER_FORMAT_KO: "Provider login only accepts letters, digits and ._-",
  SITE_NORTH_PHOTO_FILE_REQUIRED: "Attach the north photo.",
  SITE_NORTH_PHOTO_MAX_SIZE_KO: "North photo exceeds the maximum size.",
  SITE_NORTH_PHOTO_TYPE_KO: "North photo must be JPG or PNG.",
  SITE_NORTH_PHOTO_NAME_KO: "North photo name is invalid.",
  SITE_SOUTH_PHOTO_FILE_REQUIRED: "Attach the south photo.",
  SITE_SOUTH_PHOTO_MAX_SIZE_KO: "South photo exceeds the maximum size.",
  SITE_SOUTH_PHOTO_TYPE_KO: "South photo must be JPG or PNG.",
  SITE_SOUTH_PHOTO_NAME_KO: "South photo name is invalid.",
  SITE_EAST_PHOTO_FILE_REQUIRED: "Attach the east photo.",
  SITE_EAST_PHOTO_MAX_SIZE_KO: "East photo exceeds the maximum size.",
  SITE_EAST_PHOTO_TYPE_KO: "East photo must be JPG or PNG.",
  SITE_EAST_PHOTO_NAME_KO: "East photo name is invalid.",
  SITE_WEST_PHOTO_FILE_REQUIRED: "Attach the west photo.",
  SITE_WEST_PHOTO_MAX_SIZE_KO: "West photo exceeds the maximum size.",
  SITE_WEST_PHOTO_TYPE_KO: "West photo must be JPG or PNG.",
  SITE_WEST_PHOTO_NAME_KO: "West photo name is invalid.",
  NUEVO_SITE_NORTH_PHOTO_MAX_SIZE_KO: "New north photo exceeds the maximum size.",
  NUEVO_SITE_NORTH_PHOTO_TYPE_KO: "New north photo must be JPG or PNG.",
  NUEVO_SITE_NORTH_PHOTO_NAME_KO: "New north photo name is invalid.",
  NUEVO_SITE_SOUTH_PHOTO_MAX_SIZE_KO: "New south photo exceeds the maximum size.",
  NUEVO_SITE_SOUTH_PHOTO_TYPE_KO: "New south photo must be JPG or PNG.",
  NUEVO_SITE_SOUTH_PHOTO_NAME_KO: "New south photo name is invalid.",
  NUEVO_SITE_EAST_PHOTO_MAX_SIZE_KO: "New east photo exceeds the maximum size.",
  NUEVO_SITE_EAST_PHOTO_TYPE_KO: "New east photo must be JPG or PNG.",
  NUEVO_SITE_EAST_PHOTO_NAME_KO: "New east photo name is invalid.",
  NUEVO_SITE_WEST_PHOTO_MAX_SIZE_KO: "New west photo exceeds the maximum size.",
  NUEVO_SITE_WEST_PHOTO_TYPE_KO: "New west photo must be JPG or PNG.",
  NUEVO_SITE_WEST_PHOTO_NAME_KO: "New west photo name is invalid.",

  LOGIN_REQUIRED: "Login is required.",
  LOGIN_MIN_SIZE_KO: "Login must contain at least 4 characters.",
  LOGIN_MAX_SIZE_KO: "Login cannot exceed 15 characters.",
  LOGIN_FORMAT_KO: "Login only accepts letters without spaces.",
  PASSWORD_REQUIRED: "Password is required.",
  PASSWORD_MIN_SIZE_KO: "Password must contain at least 8 characters.",
  PASSWORD_MAX_SIZE_KO: "Password cannot exceed 64 characters.",
  PASSWORD_FORMAT_KO: "Password only accepts letters and digits.",
  NOMBRE_REQUIRED: "Name is required.",
  NOMBRE_MIN_SIZE_KO: "Name must contain at least 2 characters.",
  NOMBRE_MAX_SIZE_KO: "Name cannot exceed 25 characters.",
  NOMBRE_FORMAT_KO: "Name only allows letters and spaces.",
  APELLIDOS_REQUIRED: "Surname is required.",
  APELLIDOS_MIN_SIZE_KO: "Surname must contain at least 2 characters.",
  APELLIDOS_MAX_SIZE_KO: "Surname cannot exceed 35 characters.",
  APELLIDOS_FORMAT_KO: "Surname only allows letters and spaces.",
  TITULACION_REQUIRED: "Degree selection is required.",
  TITULACION_ENUM_KO: "The selected degree is invalid.",
  DNI_REQUIRED: "National ID is required.",
  DNI_FORMAT_KO: "National ID has an invalid format.",
  DNI_LETTER_KO: "National ID letter is not correct.",
  TELEFONO_REQUIRED: "Phone number is required.",
  TELEFONO_FORMAT_KO: "Phone must contain 9 digits.",
  DIRECCION_REQUIRED: "Address is required.",
  DIRECCION_MAX_SIZE_KO: "Address cannot exceed 150 characters.",
  DIRECCION_FORMAT_KO: "Address contains invalid characters.",
  EMAIL_REQUIRED: "Email is required.",
  EMAIL_FORMAT_KO: "Email has an invalid format.",
  FOTOACTO_FILE_REQUIRED: "Attach the ceremony photo.",
  FOTOACTO_MAX_SIZE_KO: "Ceremony photo exceeds the maximum size.",
  FOTOACTO_TYPE_KO: "Ceremony photo must be in JPG format.",
  FOTOACTO_NAME_KO: "Ceremony photo name is invalid.",
  NUEVO_FOTOACTO_MAX_SIZE_KO: "New ceremony photo exceeds the maximum size.",
  NUEVO_FOTOACTO_TYPE_KO: "New ceremony photo must be in JPG format.",
  NUEVO_FOTOACTO_NAME_KO: "New ceremony photo name is invalid.",
};
